version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'maksr'
      POSTGRES_PASSWORD: 'adminadmin'
      POSTGRES_DB: 'ToDo'

  backend:
    build: ./backend
    privileged: true
    restart: always
    expose:
      - 8080
    depends_on:
      - db
    command: bash -c "
        python manage.py migrate &&
        gunicorn backend.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.prod
  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx